[versions]
agp = "8.13.0"
kotlin = "2.3.0"
android-minSdk = "24"
android-compileSdk = "36"
androidx-lifecycle = "2.9.6"
vanniktechMavenPublish = "0.35.0"
compose-multiplatform = "1.9.3"
glmap = "1.12.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

#GLMap
glmap = { module = "globus:glmap", version.ref = "glmap" }
glmap-glroute = { module = "globus:glroute", version.ref = "glmap" }
glmap-glsearch = { module = "globus:glsearch", version.ref = "glmap" }

[bundles]
glmap = ["glmap", "glmap-glroute", "glmap-glsearch"]

[plugins]
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublish" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }